2 css
AndreyTrufanov/HTML-and-CSS pull request #2
Opened 2024-02-29 20:50 UTC by AndreyTrufanov

Не понимаю что делают не так с input search. Не могу поставить иконку. Не через ::before не через ::marcer. 
Также поехали отступы на мой взгляд, хотя делал все по макету. Возможно нужно было использовать еще padding, а не только margin. Но не до конца понимаю что  не так делаю.

2024-02-29 20:52 UTC, AndreyTrufanov commented
Хочу понять, вообще в том направлении я двигаюсь. Кажется что совсем сделал что-то не то....

2024-03-01 10:51 UTC, GitEsense requested changes
Форму необходимо доделать - вносите корректировки в неё тоже, она должна соответствовать макету практически полностью, инпут "моя компания"  имеет placeholder, а не label

по поводу отступов - обратите внимание на поведение и назначение отступов,
padding - это внутренние отступы от контента (расширяет блок на эти самые отступы).
margin - это отступ внешний (от блока\контента до другого), удобно для позиционирования, например margin: 24px auto = сделает отступ сверху и снизу 24px, а лево и право автоматом, margin-left:auto = выставит отступ слева на всю доступную ширину (прижать вправо), возьмём блок header
там у нас 180px отступ от layout (всегда), следовательно можно сделать padding: 0 180px, а margin: 80px auto, тем самым у нас header в центре и с отступами, но куда логичнее позиционировать сам header margin: 0 auto; padding 80px 180px;

2024-03-01 10:51 UTC, GitEsense commented on 1-Blog/1-html.html
> +            <a href="#" id="subLogo">Мой блок</a>
Ну вот тут я бы сразу объединил это под одну ссылку (иначе лого и ссылка будут иметь разные "линки", а должно срабатывать по клику одинаково, в Вашем случае я предложил бы такой вариант
```html
<div>
   <a href="#" id="logo">В</a>
   <a href="#" id="subLogo">Мой блок</a>
</div>
```
заменить на 
```html
<a href="#">
   <span id="logo">В</span>
   <span id="subLogo">Мой блог</span>
</a>
```
Но ещё лучше - это повесить стиль для "Мой блог" на ссылку, тогда второй спан не нужен будет, а span так и остаётся для стилистики буквы "В" - сделав из неё логотип

2024-03-01 10:51 UTC, GitEsense commented on 1-Blog/1-html.html
> +    <input type="search" name="search" id="search" placeholder="Поиск">
Инпут лучше поднять в header блок и оставить после nav, и есть множество вариантов на предмет иконки:
1. Вы делаете div, в котором будет img + input (img - изображение иконки, которое будем позиционировать)
2. Вы добавляете label и в него вкладываете input, на лейбл через псевдокласс добавляете контент (но тогда padding лучше перенести на сам лейбл - не самый конечно лучший вариант, но вариант.
3. Сделать блок div, в него вложить input и к это блоку сделать псевдоэлемент с позиционированием, пример 
```html
.search__field {
    display: inline-block;
    position: relative;
}
label::before {
    position: absolute;
    width: 14px;
    height: 14px;
    top: 12px;
    left: 18px;
    content: url(../images/search.svg);
}
```
Но Вы должны детально ознакомиться почему так ведёт себя и зачем сделано именно так, попробуйте разные варианты и пощупайте поведение - практика Ваш лучший друг и пробуйте свои реализации, не бойтесь экспериментировать, потом увидите проблемы и ошибки поведения при той или иной реализации
5.

2024-03-01 10:51 UTC, GitEsense commented on 1-Blog/1-html.html
>              </div>
Вот тут Вы явно перемудрили и проблемы ещё будут, сделайте упрощённый вариант и будет легче с этим работать
```html
<p>Frontend &bull; 12 мая 2024</p>
<h1>Теория цвета - Как цвет влияет на поведение потребителей</h1>
<div class="author">
   <img src="./images/girl.png" alt="Girl/Brunette" id="girl">
   <div class="author__description">
      <p class="author__name">Наталья Васильева</p>
      <p class="author__position">Разработчик</p>
</div>
```
Обратите внимание - я убрал теги заголовков (семантически будет сложно понять зачем оно) и заменил на параграфы, так же обернул в див, для компоновки элементов

2024-03-01 10:51 UTC, GitEsense commented on 1-Blog/styles/1-blog.css
> +    margin: 81px 0 80px 0;
Вот это лучше отдать именно header блоку (т.к. мы отступаем не от навигационного меню, а именно от хидер блока), а вообще лучше реализовать согласно макету через padding (будет удобнее)
```css
padding: 80px 180px;
```
цифры формальные - выставьте согласно макета (снизу точно не 80px, могу уверенно сказать, что там 69 - смотрите от input'a

2024-03-01 10:51 UTC, GitEsense commented on 1-Blog/styles/1-blog.css
> +    height: 40px;
Во-первых, у Вас ширина указана аж два раза, Во-вторых, Вы ещё и padding делаете, а так же и высоту строки, сделайте единый padding и не понадобится делать высоту инпута, а значит
height (2 раза) можно убрать, а padding сделать 9px 11px 12px 49px

2024-03-04 08:36 UTC, GitEsense requested changes
Вам необходимо повторить урок про position и отступы, желательно делать отступы сверху вниз, т.е.
header
    ---margin-bottom: 69px (например, сейчас эту задачу решает padding у header)
main
   section
   ---margin-bottom: 69px
   section
   ---margin-bottom: 69px
   footer

2024-03-04 08:36 UTC, GitEsense commented on 2-Form/styles/form.css
> +    background: linear-gradient(225deg, #fdc5c5 25.45%, #f298de 100%);
```css
background: linear-gradient(225deg, #fdc5c5 25.45%, rgba(242, 152, 222, 0) 100% ), linear-gradient(225deg, #ffa5a5 33.09%, rgba(255, 255, 255, 0) 82.34%), #f39494;
```

Это значение для заливки как в макете

2024-03-04 08:36 UTC, GitEsense commented on 2-Form/styles/form.css
> +}
Ваша проблема с формой - это то , что Вы пытаетесь все элементы выстроить через absolut position (relative), уберите везде top / left и т.п., уберите relative и верстайте блочные элементы, задавайте отступы , всё встанет на свои места - это касается абсолютно всей формы
Вы должны понимать как ведёт себя "absolute \ relative" position, чтобы не просходило такого, например с инпутом блога - мы его использовали намеренно, чтобы относительно инпута выставить в определённом месте

Так же не позиционируйте пока форму через абсолют, потом воспользуемся флекс позиционированием, так же посмотрим и на transform, сейчас достаточно поставить в центр экрана и сделать margin: 0 auto

2024-03-04 08:36 UTC, GitEsense commented on 1-Blog/styles/1-blog.css
> +    margin: 69px 0 62px 0;
Вот это всё можно убрать полностью, но повесить ограничение блока max-width:708px на секцию (родительский элемент), все вложенные блоки будут такого же размера.
То же касается и margin: 0 auto для этой же секции (выровняет по центру)
Ограничивать через height не лучший вариант для текстового блока (у Вас не влезает контент в итоге)

2024-03-04 08:36 UTC, GitEsense commented on 1-Blog/styles/1-blog.css
> +    left: 18px;
тогда уж наверное position: absolute, а position relative поставить на div.search

2024-03-04 08:36 UTC, GitEsense commented on 1-Blog/styles/1-blog.css
> +    position: absolute;
а тут убрать вовсе, мы не ставим "абсолютно" поиск

2024-03-04 08:36 UTC, GitEsense commented on 1-Blog/styles/1-blog.css
> +    height: 50px;
воспользуйтесь установкой максимальных значений (max-width, max-height)

2024-03-04 08:36 UTC, GitEsense commented on 1-Blog/styles/1-blog.css
> +}
Хорошо бы добавить margin: 0; padding: 0 по умолчанию, чтобы избавиться от стандартных отступом у блока body и ограничить размер блока и отцентровать его по экрану

а перед body можно добавить
```css
* {
   box-sizing: border-box;
}
```
Это позволит нам считать отступы частью установленного размера, а не "дополнительно", если не установить, то блок 400px на 200px + padding:50px даст размер блока 500px на 300px (ибо отступы будут считаться отдельно, а если установим border-box, то отступы будут двигать внутренний контент

2024-03-07 09:30 UTC, GitEsense requested changes
В целом всё не плохо, но в 1-Blog в первый section можно добавить text-align:center (тогда блоки выстроятся по центру), так же пересмотреть размеры блоков (оставим на флексбокс)
Сейчас главное привести форму в соответствие - её размеры, ширина и стилизация инпутов должна быть 1 к 1 (в том числе и бордер радиус, а так же между двумя инпутами 1px расстояния), когда форму сделаете - сдавайте на проверку (и проверьте отступы, у Вас строгий padding 93px, хотя я вижу сверху 72px по макету

2024-03-07 09:30 UTC, GitEsense commented on 2-Form/styles/form.css
> +    padding: 9px 102px;
лучше растянуть на весь размер формы, а стрелочку вложить в button

2024-03-07 09:30 UTC, GitEsense commented on 2-Form/styles/form.css
> +    left: 340px;
если стрелку вложить в button, то можно сменить на "right: 10px"

2024-03-07 09:30 UTC, GitEsense commented on 2-Form/styles/form.css
>  }
высоту лучше не указывать, не за чем ограничивать размер, можно указать "height:100%" и для html (родителя body), так же "height:100%"
а ширину указать как max-width, т.е. не больше

2024-03-08 14:46 UTC, GitEsense requested changes
Уже больше похоже , но нет, продолжаем, глядим на комментарии, смотрим на макет и приводит "к одному" - на выходе должен получиться такой же по размерам макет

2024-03-08 14:46 UTC, GitEsense commented on 1-Blog/styles/1-blog.css
> +}
max-width: 1440px;
    margin: 0 auto;
    не мешало бы добавить

2024-03-08 14:46 UTC, GitEsense commented on 1-Blog/styles/1-blog.css
> +    margin-bottom: 69px;
margin: 71px 0 69px;
для соответствия, если уж на то пошло)

2024-03-08 14:46 UTC, GitEsense commented on 2-Form/styles/form.css
> +    max-width: 1440px;
Мы ограничили layout , но не сделали " в центр экрана", т.е. забыли margin 0 auto (чтобы body всегда был в центре экрана)

2024-03-08 14:46 UTC, GitEsense commented on 2-Form/styles/form.css
> +    text-align: center;
либо центровку переносить в div с текстом (заголовка), либо работать дальше с учётом этого (и не дублировать, как на h1 например)

2024-03-08 14:46 UTC, GitEsense commented on 2-Form/styles/form.css
> +    height: 44px;
Даю три подсказки :
1. инпуты можно стилизовать один раз (они одинаковы), только для company поменять bacakground, а для Фамилии и имя ширину (чтобы не ломать голову - установите значение calc(50% - 1px)
Пример:
```css
input {
    line-height: 24px;
    font-style: italic;
    font-weight: 400;
    font-size: 16px;
    padding: 9px 36px 9px 11px;
    width: 100%;
    border: none;
    border-radius: 5px;
    background-color: #F5F5F5;
}
```
тогда форма инпут #company будет иметь вид:
```css
#company {
    border: 1px solid #F5F5F5;
    background-color: #fff;
}
```
а вот для Фамилии и имени - нужно будет подравнять border-radius (ведь внутренние - они ровные)
2. padding нужен для внутренних отступов, но значения там иные (если посмотреть на макет - мы увидим значения 9px 36px 9px 11px
3. Чтобы форма приняла "ожидаемый" облик - необходимо документу дать
```css
* {
   box-sizing:border-box;
}

2024-03-10 16:59 UTC, GitEsense approved these changes
В целом всё не плохо, но на флексбоксах всё должно будет стоять "на местах", рекомендую ещё раз пройтись по разделу "каскад" и повторить наследования, а так же про позиционирование не забывать, сейчас можете мерджить и продолжать

2024-03-10 16:59 UTC, GitEsense commented on 1-Blog/styles/1-blog.css
> +}
Ну так себе решение, лучше просто оставить max-width: 50px; max-height: 50px; и в перспективе расставить уже элементы через флекс например

2024-03-10 18:14 UTC, merged